name: Bump version
on:
  push:
    branches:
      - github-actions
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ALON_PAT_DRAGONEYE }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ALON_PAT_DRAGONEYE }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Update version.py
        run: sh bump_version.sh
