name: Create a new release

on: [workflow_dispatch]

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ALON_PAT_DRAGONEYE }}
    - name: get new version
      uses: anothrNick/github-tag-action@master
      id: get_new_tag
      env:
        GITHUB_TOKEN: ${{ secrets.ALON_PAT_DRAGONEYE }}
        WITH_V: true
        DEFAULT_BUMP: patch
        DRY_RUN: true
    - name: Update version.py
      run: |
        version_file="dragoneye/version.py"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "latest tag: ${{steps.get_new_tag.outputs.new_tag}}"
        echo "__version__ = '${{steps.get_new_tag.outputs.new_tag}}'" > $version_file
        git commit --reuse-message=HEAD $version_file || echo "No changes to commit"
        git push origin
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.ALON_PAT_DRAGONEYE }}
        WITH_V: true
        DEFAULT_BUMP: patch

  create-new-release:
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
    - name: update docs and bump version
      env:
        GITHUB_TOKEN: ${{ secrets.ALON_PAT_DRAGONEYE }}
      run: |
        gh release create ${{steps.get_new_tag.outputs.new_tag}}  -t ${{steps.get_new_tag.outputs.new_tag}} --repo indeni/dragoneye

  release-packadge-to-pipy:
    needs: [create-new-release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel twine pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Upload pip package to PyPi
      run: |
        python setup.py sdist bdist_wheel --version ${{steps.get_new_tag.outputs.new_tag}}
        twine upload dist/*  -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}